server:
  port: 8761


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
  instance:
    appname: eurekaServerApp
    hostname: peer1
#    preferIpAddress: true

spring:
  application:
    name: eurekaServer