spring:
  application:
    name: zuul

server:
  port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

zuul:
  #  ignoredServices: '*'
  routes:
#    EUREKASERVER: /**
    EUREKASERVER: /eureka/**