server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://peer1:8761/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
  instance:
    appname: eurekaServerRepl
    hostname: peer2

spring:
  application:
    name: eurekaServerRepl